## Machine Learning ElasticNet
---------------------------------------------------------
### Gas Production (from 1970-2018)
* Goal: Predict the next five years 2019-2023 compare MSE and R-Square to other machine learning models

In [1]:
# Import dependencies
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.linear_model import ElasticNet
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

### Reading, cleaning, and transforming the data with features into a single dataframe

In [2]:
# Read the 'gas production' csv file into a pandas DataFrame
gas_prod = pd.read_csv('../data/clean_data/Gas Production - EJ-YearFixed-Python.csv')
# Replace all the blanks (or NaN) with zero
clean_gas_prod = gas_prod.replace(np.nan,0)
# Read the 'world population' csv file into pandas; adding in 'Population' feature
global_pop = pd.read_csv('../data/clean_data/WorldPopulationbyYear.csv')
# Merge the 'gas production' with 'world population by year'
gas_pop = global_pop.merge(clean_gas_prod, on="Year")
# Renaming columns 
# new_df = df.rename(columns={"A": "a", "B": "c"})
gas_pop = gas_pop.rename(columns={"World": "World Population",
                                  "Total World": "World Exajoules"})
# Adding in 'GDP' as a feature
# Read the 'GDP' csv file into pandas
gdp_percent = pd.read_csv('../data/clean_data/GDP%-YearFixed-Python.csv', encoding = 'ISO-8859-1')
# Replace all the blanks (or NaN) with zero
clean_gdp_percent = gdp_percent.replace(np.nan,0)
filtered_gdp = clean_gdp_percent[['Year', 'United States', 'World']]
filtered_gdp = filtered_gdp.rename(columns={'United States': 'US GDP (%)',
                                            'World': 'World GDP (%)'})
# Merge the latest dataframe with 'filtered GDP'
gas_prod_v1 = filtered_gdp.merge(gas_pop, on="Year")
# Adding in 'Inflation' as a feature
# Read the 'Inflation' csv file into pandas
inflation = pd.read_csv('../data/clean_data/InflationAnnual%-YearFixed-Python.csv', encoding = 'ISO-8859-1')
# Replace all the blanks (or NaN) with zero
clean_inf = inflation.replace(np.nan,0)
filtered_inf = clean_inf[['Year', 'United States', 'World']]
filtered_inf = filtered_inf.rename(columns={'United States': 'US Inflation (Annual %)',
                                            'World': 'World Inflation (Annual %)'})
# Merge the latest dataframe with 'filtered inflation'
gas_prod_v2 = filtered_inf.merge(gas_prod_v1, on="Year")
# Adding in 'Taxes on goods & services' as a feature
# Read the 'Taxes' csv file into pandas
taxes = pd.read_csv('../data/clean_data/Taxes%-YearFixed-Python.csv', encoding = 'ISO-8859-1')
# Replace all the blanks (or NaN) with zero
clean_tax = taxes.replace(np.nan,0)
filtered_tax = clean_tax[['Year', 'United States', 'World']]
filtered_tax = filtered_tax.rename(columns={'United States': 'US Tax (% on Goods & Services)',
                                            'World': 'World Tax (% on Goods & Services)'})
# Merge the latest dataframe with 'filtered taxes'
df = filtered_tax.merge(gas_prod_v2, on="Year")
# Dropping 2019 due to incomplete data; getting a prediction for 2019 up to 2023
df = df[df['Year'] <= 2018]
df

,Year,US Tax (% on Goods & Services),World Tax (% on Goods & Services),US Inflation (Annual %),World Inflation (Annual %),US GDP (%),World GDP (%),World Population,Algeria,Argentina,...,Turkmenistan,Ukraine,United Arab Emirates,United Kingdom,US,USSR,Uzbekistan,Venezuela,Vietnam,Yemen
0,1970,0.000000,0.000000,5.838255,0.000000,21.414736,26.911121,3682911039,0.09,0.21,...,0.00,0.00,0.03,0.39,20.57,6.75,0.00,0.31,0.00,0.00
1,1971,0.000000,0.000000,4.292767,0.000000,21.919818,26.526697,3760509002,0.09,0.23,...,0.00,0.00,0.05,0.66,21.16,7.24,0.00,0.30,0.00,0.00
2,1972,7.143859,0.000000,3.272278,0.000000,22.580622,26.164536,3836892580,0.12,0.22,...,0.00,0.00,0.05,0.95,21.09,7.55,0.00,0.30,0.00,0.00
3,1973,6.579487,0.000000,6.177760,0.000000,23.331809,27.054172,3912347640,0.16,0.24,...,0.00,0.00,0.06,1.03,21.07,8.06,0.00,0.37,0.00,0.00
4,1974,5.990202,0.000000,11.054805,0.000000,22.694942,27.896165,3988478324,0.18,0.25,...,0.00,0.00,0.06,1.24,20.14,8.89,0.00,0.39,0.00,0.00
5,1975,5.626993,0.000000,9.143147,0.000000,20.277476,25.909123,4062864562,0.22,0.27,...,0.00,0.00,0.06,1.29,18.65,9.86,0.00,0.38,0.00,0.00
6,1976,5.410532,0.000000,5.744813,0.000000,22.038398,26.450586,4135418002,0.28,0.26,...,0.00,0.00,0.07,1.36,18.50,10.94,0.00,0.47,0.00,0.00
7,1977,4.678032,0.000000,6.501684,0.000000,23.526270,26.629795,4207766711,0.27,0.27,...,0.00,0.00,0.14,1.43,18.58,11.80,0.00,0.51,0.00,0.00
8,1978,4.357011,0.000000,7.630964,0.000000,24.831785,27.184231,4281312782,0.41,0.27,...,0.00,0.00,0.20,1.37,18.50,12.69,0.00,0.51,0.00,0.00
9,1979,3.794360,0.000000,11.254471,0.000000,25.111120,27.392791,4356746035,0.68,0.25,...,0.00,0.00,0.21,1.38,19.06,13.87,0.00,0.57,0.00,0.00
10,1980,4.411226,0.000000,13.549202,0.000000,23.310271,26.883838,4432925590,0.55,0.29,...,0.00,0.00,0.26,1.31,18.90,14.84,0.00,0.59,0.00,0.00
11,1981,6.358336,0.000000,10.334715,12.482070,24.276857,26.389981,4511137170,0.64,0.31,...,0.00,0.00,0.31,1.31,18.71,15.87,0.00,0.59,0.00,0.00
12,1982,5.478995,0.000000,6.131427,10.221727,22.070083,25.109031,4592341169,0.84,0.34,...,0.00,0.00,0.33,1.33,17.39,17.07,0.00,0.63,0.00,0.00
13,1983,5.384804,0.000000,3.212435,8.669272,22.252987,24.601174,4674266079,1.20,0.46,...,0.00,0.00,0.29,1.37,15.76,18.27,0.00,0.62,0.00,0.00
14,1984,5.157868,0.000000,4.300535,8.217653,25.095818,25.344400,4755914211,1.22,0.47,...,0.00,0.00,0.39,1.34,17.10,20.03,0.00,0.69,0.00,0.00
15,1985,4.506918,0.000000,3.545644,6.807567,24.188340,25.319454,4839074592,1.34,0.49,...,2.83,1.46,0.46,1.50,16.12,0.00,1.18,0.69,0.00,0.00
16,1986,3.947416,0.000000,1.898048,5.823107,23.740625,25.095420,4924736807,1.37,0.54,...,2.89,1.35,0.53,1.57,15.71,0.00,1.32,0.76,0.00,0.00
17,1987,3.518278,0.000000,3.664563,5.756464,23.620231,25.373399,5012555212,1.55,0.53,...,3.00,1.21,0.59,1.65,16.27,0.00,1.36,0.74,0.00,0.00
18,1988,3.638177,0.000000,4.077741,7.196970,22.827808,26.239090,5101297281,1.62,0.63,...,3.01,1.10,0.61,1.58,16.71,0.00,1.36,0.76,0.00,0.00
19,1989,3.208638,0.000000,4.827003,6.999093,22.513799,26.624424,5189996799,1.75,0.66,...,3.06,1.05,0.72,1.55,16.95,0.00,1.40,0.78,0.00,0.00
20,1990,3.212851,0.000000,5.397956,8.215536,21.529213,25.923266,5280076284,1.86,0.62,...,2.85,0.96,0.71,1.71,17.40,0.00,1.33,0.88,0.00,0.00
21,1991,3.609554,0.000000,4.234964,8.996939,20.110605,25.392887,5368065408,2.01,0.70,...,2.74,0.83,0.84,1.91,17.31,0.00,1.36,0.88,0.00,0.00
22,1992,3.898273,0.000000,3.028820,7.636109,20.077582,25.210322,5452349932,2.09,0.70,...,1.81,0.72,0.78,1.94,17.45,0.00,1.38,0.86,0.01,0.00
23,1993,3.840156,0.000000,2.951657,7.144587,20.393628,24.917159,5537511534,2.11,0.75,...,2.12,0.65,0.81,2.28,17.65,0.00,1.46,0.93,0.01,0.00
24,1994,4.106130,0.000000,2.607442,10.143683,21.279097,24.930955,5621787194,1.94,0.78,...,1.16,0.62,0.91,2.44,18.37,0.00,1.53,0.99,0.01,0.00
25,1995,3.967159,0.000000,2.805420,9.073536,21.272649,24.806326,5706689090,2.21,0.88,...,1.05,0.58,1.10,2.67,18.12,0.00,1.56,1.10,0.01,0.00
26,1996,3.493396,0.000000,2.931204,6.550973,21.701815,24.650589,5789623839,2.35,1.01,...,1.14,0.58,1.19,3.17,18.37,0.00,1.59,1.19,0.01,0.00
27,1997,3.366138,0.000000,2.337690,5.536007,22.409709,24.676491,5872254361,2.69,0.96,...,0.56,0.59,1.27,3.23,18.42,0.00,1.63,1.23,0.02,0.00
28,1998,3.140164,33.792780,1.552279,5.110250,22.958333,24.418578,5954005524,2.89,1.04,...,0.43,0.57,1.30,3.40,18.62,0.00,1.78,1.29,0.03,0.00
29,1999,3.617373,0.000000,2.188027,3.079499,23.420368,24.101122,6034491778,3.24,1.21,...,0.74,0.58,1.35,3.73,18.36,0.00,1.81,1.10,0.05,0.00
30,2000,3.182633,0.000000,3.376857,3.494465,23.675148,24.448252,6114332536,3.31,1.31,...,1.53,0.57,1.35,4.08,18.67,0.00,1.83,1.12,0.06,0.00
31,2001,3.129721,33.039462,2.826171,3.878938,22.176948,23.948517,6193671787,3.11,1.30,...,1.67,0.58,1.38,3.99,19.15,0.00,1.85,1.18,0.07,0.00
32,2002,3.517331,32.575330,1.586032,2.907999,21.708139,23.358527,6272752974,3.20,1.26,...,1.74,0.64,1.52,3.91,18.40,0.00,1.90,1.14,0.08,0.00
33,2003,3.573926,33.607547,2.270095,3.020643,21.742224,23.817492,6351882361,3.38,1.44,...,1.92,0.66,1.57,3.88,18.64,0.00,1.91,1.01,0.08,0.00
34,2004,3.496313,34.915823,2.677237,3.382647,22.658575,24.685993,6431551644,3.31,1.57,...,1.90,0.70,1.62,3.63,18.11,0.00,1.94,1.14,0.14,0.00
35,2005,3.167210,34.949972,3.392747,4.112184,23.380303,24.921953,6511748367,3.06,1.60,...,2.05,0.71,1.68,3.32,17.62,0.00,1.97,1.10,0.22,0.00
36,2006,2.817742,33.734591,3.225944,4.267175,23.539185,25.404324,6592734542,2.93,1.61,...,2.04,0.72,1.71,3.01,18.06,0.00,2.04,1.26,0.24,0.00
37,2007,2.436469,33.746476,2.852672,4.827047,22.592492,25.791610,6674203658,2.94,1.57,...,2.22,0.72,1.77,2.72,18.79,0.00,2.12,1.34,0.25,0.00
38,2008,2.472901,32.268633,3.839100,8.949953,21.119017,25.620517,6756917904,2.97,1.54,...,2.22,0.73,1.76,2.62,19.66,0.00,2.20,1.20,0.26,0.00
39,2009,3.008888,31.557385,-0.355546,2.928564,17.804581,23.391521,6839574284,2.76,1.45,...,1.20,0.73,1.71,2.20,20.07,0.00,2.10,1.14,0.28,0.03
40,2010,2.759912,31.875890,1.640043,3.326345,18.743104,24.207113,6921871614,2.79,1.40,...,1.44,0.70,1.80,2.08,20.71,0.00,2.06,1.10,0.33,0.23
41,2011,2.956038,33.264196,3.156842,4.839403,19.103526,24.547417,7002860604,2.87,1.36,...,2.03,0.70,1.84,1.66,22.22,0.00,2.04,1.09,0.29,0.34
42,2012,2.991670,33.271756,2.069337,3.707818,20.020890,24.404915,7085763408,2.82,1.32,...,2.12,0.70,1.91,1.41,23.37,0.00,2.03,1.15,0.32,0.27
43,2013,2.840751,32.787076,1.464833,2.605818,20.413743,24.310278,7169640142,2.86,1.24,...,2.12,0.73,1.92,1.33,23.60,0.00,2.01,1.10,0.34,0.37
44,2014,2.978668,33.191709,1.622223,2.346269,20.812680,24.470283,7254228377,2.89,1.24,...,2.29,0.73,1.90,1.35,25.37,0.00,2.03,1.14,0.35,0.35
45,2015,2.940638,33.724915,0.118627,1.393330,21.099052,24.297531,7338964960,2.93,1.28,...,2.37,0.68,2.11,1.46,26.65,0.00,1.93,1.30,0.37,0.10
46,2016,2.832608,34.248831,1.261583,1.486007,20.387569,23.913640,7424282488,3.29,1.34,...,2.28,0.68,2.17,1.50,26.18,0.00,1.91,1.34,0.37,0.02
47,2017,2.366356,33.333664,2.130110,2.233522,20.658987,24.222791,7509065705,3.35,1.34,...,2.11,0.70,2.24,1.51,26.86,0.00,1.92,1.39,0.34,0.02
48,2018,3.044843,34.011405,2.442583,2.458142,21.021222,24.382773,7591932907,3.38,1.42,...,2.21,0.71,2.21,1.46,30.09,0.00,2.06,1.14,0.35,0.02

### Scaling and training the data using SKLearn ElasticNet and StandardScaler

In [3]:
# # ElasticNet model
# # Note: Use an alpha of .01 when creating the model for this activity
# from sklearn.linear_model import ElasticNet

# ### BEGIN SOLUTION
# elasticnet = ElasticNet(alpha=.01).fit(X_train_scaled, y_train_scaled)

# predictions = elasticnet.predict(X_test_scaled)

# MSE = mean_squared_error(y_test_scaled, predictions)
# r2 = elasticnet.score(X_test_scaled, y_test_scaled)
# ### END SOLUTION

# print(f"MSE: {MSE}, R2: {r2}")

In [4]:
# Create the model
model = ElasticNet(alpha=.01)

### One-Step-Ahead Forecast

In [5]:
# Using 2000 - 2009 data to run historical prediction from 2001 - 2010
predict_0110=[]

for year in range(10):
    i = 31 + year

    # Does not need .value.reshape(-1, 1) as there's dimension now with 2+ features
    hist_X = df[["World Population",
                 "World GDP (%)",
                 "World Inflation (Annual %)",
                 "World Tax (% on Goods & Services)"]]
    hist_y = df["World Exajoules"].values.reshape(-1, 1)
    X_scaler = StandardScaler().fit(hist_X)
    y_scaler = StandardScaler().fit(hist_y)
    X_train_scaled = X_scaler.transform(hist_X)
    y_train_scaled = y_scaler.transform(hist_y)
    X_train_scaled = pd.DataFrame(X_train_scaled)
    
    # Fitting 1980-2000 therefore, i-21 on the first iteration and so on up to 10x
    elasticnet = model.fit(X_train_scaled.iloc[(i-21):i], y_train_scaled[(i-21):i])
    
    # Changed reshape to (1, -1)
    gas_predict = elasticnet.predict(X_train_scaled.iloc[i-1].values.reshape(1, -1))
    predict_0110.append(gas_predict.flatten()[0])
    
# Invert predict_0110 so it's not scaled for later comparison
inverse_predict_0110 = y_scaler.inverse_transform(predict_0110)

print(inverse_predict_0110)

[ 84.44955945  86.26525411  88.72014524  91.22203662  93.42462832
  95.96359748  99.19286207 102.38770294 105.2827448  102.95065459]

### Historical Prediction MSE and R-Square

In [6]:
# Use our model to make predictions
predicted = elasticnet.predict(X_train_scaled)

inverse_predicted = y_scaler.inverse_transform(predicted)

hist_mse = mean_squared_error(y_train_scaled, predicted)
hist_r2 = elasticnet.score(X_train_scaled, y_train_scaled)

print(f"-----------------Historical-----------------")
print(f"Mean Squared Error (MSE): {hist_mse}")
print(f"R-squared (R2): {hist_r2}")

-----------------Historical-----------------
Mean Squared Error (MSE): 0.027061073957711537
R-squared (R2): 0.9729389260422884

### Historical Predictions

In [7]:
historical_comps_0110 = df.loc[df["Year"].between(2001, 2010), ["Year", "World Exajoules"]]
historical_comps_0110["Prediction"] = inverse_predict_0110
historical_comps_0110["Difference"] = historical_comps_0110["Prediction"] - historical_comps_0110["World Exajoules"]
historical_comps_0110["% Difference"] = ((historical_comps_0110["Prediction"] - historical_comps_0110["World Exajoules"])/historical_comps_0110["World Exajoules"]) * 100
historical_comps_0110

    Year  World Exajoules  Prediction  Difference  % Difference
31  2001            88.51   84.449559   -4.060441     -4.587550
32  2002            90.54   86.265254   -4.274746     -4.721389
33  2003            93.79   88.720145   -5.069855     -5.405539
34  2004            96.86   91.222037   -5.637963     -5.820734
35  2005            99.16   93.424628   -5.735372     -5.783957
36  2006           102.53   95.963597   -6.566403     -6.404372
37  2007           105.16   99.192862   -5.967138     -5.674342
38  2008           109.06  102.387703   -6.672297     -6.118006
39  2009           105.66  105.282745   -0.377255     -0.357046
40  2010           113.26  102.950655  -10.309345     -9.102371

### Exporting Historical Predictions to CSV
* Find it in the 'clean_data' folder within 'data'

In [8]:
# Saving historical predictions to a csv file
historical_comps_0110.to_csv('../data/clean_data/gas_outputs/GasProduction_Historical_ElasticNetModel_2001_2010.csv', index=False)

### Calculating the moving averages for the features from 2019-2023

In [9]:
# Narrow down data frame to the specific year range of 2010 - 2018
MA = df.loc[df["Year"].between(2010, 2018), ["Year",
                                             "World Population",
                                             "World Exajoules",
                                             "World GDP (%)",
                                             "World Inflation (Annual %)",
                                             "World Tax (% on Goods & Services)"]]
MA

,Year,World Population,World Exajoules,World GDP (%),World Inflation (Annual %),World Tax (% on Goods & Services)
40,2010,6921871614,113.26,24.207113,3.326345,31.875890
41,2011,7002860604,117.07,24.547417,4.839403,33.264196
42,2012,7085763408,119.48,24.404915,3.707818,33.271756
43,2013,7169640142,120.88,24.310278,2.605818,32.787076
44,2014,7254228377,123.33,24.470283,2.346269,33.191709
45,2015,7338964960,126.02,24.297531,1.393330,33.724915
46,2016,7424282488,127.45,23.913640,1.486007,34.248831
47,2017,7509065705,132.21,24.222791,2.233522,33.333664
48,2018,7591932907,138.87,24.382773,2.458142,34.011405

In [10]:
# Iterate 5 times through 5 years (2019-2023) of the features' moving averages
for i in range(5):
    starting_index = 4 + i
    year_inc = 2018 + i
    new_year = year_inc + 1

    pop_mean = MA['World Population'].iloc[starting_index:starting_index+5].mean()
    gdp_mean = MA['World GDP (%)'].iloc[starting_index:starting_index+5].mean()
    inf_mean = MA['World Inflation (Annual %)'].iloc[starting_index:starting_index+5].mean()
    tax_mean = MA['World Tax (% on Goods & Services)'].iloc[starting_index:starting_index+5].mean()

    df = pd.DataFrame({"Year":[new_year],
                       "World Population": [pop_mean],
                       "World Exajoules": 0,
                       "World GDP (%)": [gdp_mean],
                       "World Inflation (Annual %)": [inf_mean],
                       "World Tax (% on Goods & Services)": [tax_mean]})
    
    MA = MA.append(df, ignore_index=True)
    del df
MA

,Year,World Population,World Exajoules,World GDP (%),World Inflation (Annual %),World Tax (% on Goods & Services)
0,2010,6.921872e+09,113.26,24.207113,3.326345,31.875890
1,2011,7.002861e+09,117.07,24.547417,4.839403,33.264196
2,2012,7.085763e+09,119.48,24.404915,3.707818,33.271756
3,2013,7.169640e+09,120.88,24.310278,2.605818,32.787076
4,2014,7.254228e+09,123.33,24.470283,2.346269,33.191709
5,2015,7.338965e+09,126.02,24.297531,1.393330,33.724915
6,2016,7.424282e+09,127.45,23.913640,1.486007,34.248831
7,2017,7.509066e+09,132.21,24.222791,2.233522,33.333664
8,2018,7.591933e+09,138.87,24.382773,2.458142,34.011405
9,2019,7.423695e+09,0.00,24.257404,1.983454,33.702105
10,2020,7.457588e+09,0.00,24.214828,1.910891,33.804184
11,2021,7.481313e+09,0.00,24.198287,2.014403,33.820038
12,2022,7.492719e+09,0.00,24.255216,2.120082,33.734279
13,2023,7.489450e+09,0.00,24.261702,2.097394,33.814402

### Multi-Step Forecast

In [11]:
future_predict = []

# Updates: relocated some sections of code
future_X = MA[["World Population",
                 "World GDP (%)",
                 "World Inflation (Annual %)",
                 "World Tax (% on Goods & Services)"]]
future_y = MA["World Exajoules"].values.reshape(-1, 1)
X_scaler = StandardScaler().fit(future_X)
y_scaler = StandardScaler().fit(future_y[0:9])
X_test_scaled = X_scaler.transform(future_X)
y_test_scaled = y_scaler.transform(future_y[0:9])
X_test_scaled_df = pd.DataFrame(X_test_scaled)
y_test_scaled_df = pd.DataFrame(y_test_scaled)

for year in range(5):
    i = 9 + year

    elasticnet = model.fit(X_test_scaled_df.iloc[year:i], y_test_scaled_df.iloc[year:i+1])
    gas_predict_2 = elasticnet.predict(X_test_scaled_df.iloc[i-1].values.reshape(1, -1))
    df2 = pd.DataFrame(pd.Series(gas_predict_2.flatten()[0]))
    future_predict.append(gas_predict_2.flatten()[0])
    
    y_test_scaled_df = y_test_scaled_df.append(df2, ignore_index=True)
    del df2

# Invert future_predict so it's not scaled for later comoparison
inverse_future_predict = y_scaler.inverse_transform(future_predict)

print(inverse_future_predict)

[136.91408404 130.88426677 131.81303124 132.60577726 133.29604443]

### Future Prediction MSE and R-Square (( REMOVING THIS SECTION ))

In [12]:
# # Use our model to make predictions
# future_predicted = elasticnet.predict(X_test_scaled)

# inverse_future_predicted = y_scaler.inverse_transform(predicted)

# future_mse = mean_squared_error(y_test_scaled, future_predicted)
# future_r2 = elasticnet.score(X_test_scaled, y_test_scaled)

# print(f"------------------Future------------------")
# print(f"Mean Squared Error (MSE): {future_mse}")
# print(f"R-squared (R2): {future_r2}")

### Predictions for Future 'World Exajoules' according to the ML
#### (( REMOVED 'World Exajoules' column ))

In [13]:
future_comps_19_23 = MA.loc[MA["Year"].between(2019, 2023), ["Year"]]
future_comps_19_23["Prediction"] = inverse_future_predict
future_comps_19_23

    Year  Prediction
9   2019  136.914084
10  2020  130.884267
11  2021  131.813031
12  2022  132.605777
13  2023  133.296044

### Exporting Future Predictions to CSV
* Find it in the 'clean_data' folder within 'data'

In [14]:
# Saving future predictions to a csv file
future_comps_19_23.to_csv('../data/clean_data/gas_outputs/GasProduction_Future_ElasticNetModel_2019_2023.csv', index=False)

### Building a Summary Table for MSE and R-Square

In [15]:
# Building a summary table for the MSE and R^2 for both historical and future
stats = [["Multiple Regression",
          hist_mse,
#           future_mse,
          hist_r2 #,
#           future_r2
         ]]
score_summary = pd.DataFrame(stats, columns = ["Model",
                                               "Historical MSE",
#                                                "Future MSE",
                                               "Historical R-Square" #,
#                                                "Future R-Square"
                                              ])
score_summary

                 Model  Historical MSE  Historical R-Square
0  Multiple Regression        0.027061             0.972939

### Exporting Summary Table for MSE and R-Square
* Find it in the 'gas_outputs' folder within 'clean_data'

In [16]:
score_summary.to_csv('../data/clean_data/gas_outputs/GasProduction_MSE_R2_ElasticNet_Table.csv', index=False)