In [1]:
import pandas as pd
import numpy as np

In [2]:
oil_barrels = "oil-production-consumption.csv"

In [3]:
oil_barrels_df  = pd.read_csv(oil_barrels)
oil_barrels_df

,Thousand barrels daily,1965,1966,1967,1968,1969,1970,1971,1972,1973,...,2013,2014,2015,2016,2017,2018,2019,2019.1,2008-18,2019.2
0,Canada,1108.0,1167.0,1246.0,1322.0,1380.0,1472.0,1512.0,1589.0,1682.0,...,2345.0,2387.0,2347.0,2393.0,2393.0,2443.0,2403.0,-1.70%,0.60%,2.40%
1,Mexico,316.0,333.0,357.0,386.0,410.0,441.0,467.0,523.0,564.0,...,2034.0,1960.0,1939.0,1950.0,1883.0,1821.0,1733.0,-4.80%,-1.30%,1.80%
2,US,11522.0,12100.0,12567.0,13405.0,14153.0,14710.0,15223.0,16381.0,17318.0,...,18006.0,18136.0,18524.0,18618.0,18883.0,19428.0,19400.0,-0.10%,0.30%,19.70%
3,Total North America,12946.0,13601.0,14170.0,15113.0,15943.0,16622.0,17202.0,18493.0,19564.0,...,22385.0,22483.0,22810.0,22961.0,23160.0,23692.0,23536.0,-0.70%,0.20%,23.90%
4,Argentina,432.0,447.0,460.0,469.0,492.0,448.0,480.0,479.0,483.0,...,658.0,643.0,662.0,651.0,637.0,611.0,599.0,-2.00%,1.20%,0.60%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Thailand,48.0,56.0,62.0,81.0,88.0,103.0,114.0,143.0,151.0,...,1267.0,1270.0,1330.0,1364.0,1407.0,1432.0,1453.0,1.50%,3.60%,1.50%
96,Vietnam,31.0,69.0,100.0,102.0,124.0,128.0,109.0,112.0,110.0,...,398.0,409.0,452.0,470.0,487.0,506.0,528.0,4.40%,5.40%,0.50%
97,Other Asia Pacific,60.0,63.0,67.0,71.0,75.0,78.0,81.0,91.0,90.0,...,357.0,388.0,425.0,437.0,454.0,474.0,506.0,6.70%,6.80%,0.50%
98,Total Asia Pacific,3205.0,3693.0,4300.0,4902.0,5715.0,6646.0,7393.0,7940.0,9058.0,...,30560.0,31105.0,32344.0,33519.0,34669.0,35457.0,36178.0,2.00%,3.20%,36.80%
99,Total World,30771.0,33137.0,35503.0,38420.0,41727.0,45313.0,47886.0,51430.0,55577.0,...,90152.0,90903.0,92610.0,94404.0,96013.0,97348.0,98272.0,0.90%,1.30%,100.00%

In [4]:
clean1 = oil_barrels_df.replace(np.nan,0)
clean1

,Thousand barrels daily,1965,1966,1967,1968,1969,1970,1971,1972,1973,...,2013,2014,2015,2016,2017,2018,2019,2019.1,2008-18,2019.2
0,Canada,1108.0,1167.0,1246.0,1322.0,1380.0,1472.0,1512.0,1589.0,1682.0,...,2345.0,2387.0,2347.0,2393.0,2393.0,2443.0,2403.0,-1.70%,0.60%,2.40%
1,Mexico,316.0,333.0,357.0,386.0,410.0,441.0,467.0,523.0,564.0,...,2034.0,1960.0,1939.0,1950.0,1883.0,1821.0,1733.0,-4.80%,-1.30%,1.80%
2,US,11522.0,12100.0,12567.0,13405.0,14153.0,14710.0,15223.0,16381.0,17318.0,...,18006.0,18136.0,18524.0,18618.0,18883.0,19428.0,19400.0,-0.10%,0.30%,19.70%
3,Total North America,12946.0,13601.0,14170.0,15113.0,15943.0,16622.0,17202.0,18493.0,19564.0,...,22385.0,22483.0,22810.0,22961.0,23160.0,23692.0,23536.0,-0.70%,0.20%,23.90%
4,Argentina,432.0,447.0,460.0,469.0,492.0,448.0,480.0,479.0,483.0,...,658.0,643.0,662.0,651.0,637.0,611.0,599.0,-2.00%,1.20%,0.60%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Thailand,48.0,56.0,62.0,81.0,88.0,103.0,114.0,143.0,151.0,...,1267.0,1270.0,1330.0,1364.0,1407.0,1432.0,1453.0,1.50%,3.60%,1.50%
96,Vietnam,31.0,69.0,100.0,102.0,124.0,128.0,109.0,112.0,110.0,...,398.0,409.0,452.0,470.0,487.0,506.0,528.0,4.40%,5.40%,0.50%
97,Other Asia Pacific,60.0,63.0,67.0,71.0,75.0,78.0,81.0,91.0,90.0,...,357.0,388.0,425.0,437.0,454.0,474.0,506.0,6.70%,6.80%,0.50%
98,Total Asia Pacific,3205.0,3693.0,4300.0,4902.0,5715.0,6646.0,7393.0,7940.0,9058.0,...,30560.0,31105.0,32344.0,33519.0,34669.0,35457.0,36178.0,2.00%,3.20%,36.80%
99,Total World,30771.0,33137.0,35503.0,38420.0,41727.0,45313.0,47886.0,51430.0,55577.0,...,90152.0,90903.0,92610.0,94404.0,96013.0,97348.0,98272.0,0.90%,1.30%,100.00%

In [5]:
clean2 = clean1.replace('-', np.nan)
clean2

,Thousand barrels daily,1965,1966,1967,1968,1969,1970,1971,1972,1973,...,2013,2014,2015,2016,2017,2018,2019,2019.1,2008-18,2019.2
0,Canada,1108.0,1167.0,1246.0,1322.0,1380.0,1472.0,1512.0,1589.0,1682.0,...,2345.0,2387.0,2347.0,2393.0,2393.0,2443.0,2403.0,-1.70%,0.60%,2.40%
1,Mexico,316.0,333.0,357.0,386.0,410.0,441.0,467.0,523.0,564.0,...,2034.0,1960.0,1939.0,1950.0,1883.0,1821.0,1733.0,-4.80%,-1.30%,1.80%
2,US,11522.0,12100.0,12567.0,13405.0,14153.0,14710.0,15223.0,16381.0,17318.0,...,18006.0,18136.0,18524.0,18618.0,18883.0,19428.0,19400.0,-0.10%,0.30%,19.70%
3,Total North America,12946.0,13601.0,14170.0,15113.0,15943.0,16622.0,17202.0,18493.0,19564.0,...,22385.0,22483.0,22810.0,22961.0,23160.0,23692.0,23536.0,-0.70%,0.20%,23.90%
4,Argentina,432.0,447.0,460.0,469.0,492.0,448.0,480.0,479.0,483.0,...,658.0,643.0,662.0,651.0,637.0,611.0,599.0,-2.00%,1.20%,0.60%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Thailand,48.0,56.0,62.0,81.0,88.0,103.0,114.0,143.0,151.0,...,1267.0,1270.0,1330.0,1364.0,1407.0,1432.0,1453.0,1.50%,3.60%,1.50%
96,Vietnam,31.0,69.0,100.0,102.0,124.0,128.0,109.0,112.0,110.0,...,398.0,409.0,452.0,470.0,487.0,506.0,528.0,4.40%,5.40%,0.50%
97,Other Asia Pacific,60.0,63.0,67.0,71.0,75.0,78.0,81.0,91.0,90.0,...,357.0,388.0,425.0,437.0,454.0,474.0,506.0,6.70%,6.80%,0.50%
98,Total Asia Pacific,3205.0,3693.0,4300.0,4902.0,5715.0,6646.0,7393.0,7940.0,9058.0,...,30560.0,31105.0,32344.0,33519.0,34669.0,35457.0,36178.0,2.00%,3.20%,36.80%
99,Total World,30771.0,33137.0,35503.0,38420.0,41727.0,45313.0,47886.0,51430.0,55577.0,...,90152.0,90903.0,92610.0,94404.0,96013.0,97348.0,98272.0,0.90%,1.30%,100.00%

In [7]:
clean2.to_csv ('./clean_data/final_oil_barrel_consumption.csv')