In [2]:
import pandas as pd

In [3]:
oil_barrels = "oil-production-barrels.csv"

In [4]:
oil_barrels_df  = pd.read_csv(oil_barrels)
oil_barrels_df

,Thousand barrels daily,1965,1966,1967,1968,1969,1970,1971,1972,1973,...,2013,2014,2015,2016,2017,2018,2019,2019.1,2008-18,2019.2
0,Canada,920,1012,1106,1194,1306,1473,1582,1829,2114,...,4128.0,4418.0,4572.0,4655.0,5037.0,5501.0,5651.0,2.7%,5.1%,5.9%
1,Mexico,362,370,411,439,461,487,486,506,525,...,2875.0,2784.0,2587.0,2456.0,2224.0,2068.0,1918.0,-7.3%,-4.2%,2.0%
2,US,9014,9579,10219,10600,10828,11297,11156,11185,10946,...,10099.0,11801.0,12781.0,12349.0,13135.0,15360.0,17045.0,11.0%,8.5%,17.9%
3,Total North America,10296,10961,11736,12233,12595,13257,13224,13520,13585,...,17101.0,19004.0,19940.0,19460.0,20396.0,22929.0,24614.0,7.3%,5.6%,25.9%
4,Argentina,276,293,319,348,362,399,432,444,434,...,644.0,638.0,646.0,610.0,590.0,591.0,620.0,4.9%,-3.0%,0.7%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,Thailand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,466.0,464.0,481.0,489.0,486.0,478.0,477.0,-0.1%,2.6%,0.5%
60,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,346.0,325.0,352.0,317.0,284.0,257.0,236.0,-7.9%,-1.9%,0.2%
61,Other Asia Pacific,35,34,31,35,36,40,42,44,47,...,274.0,296.0,298.0,281.0,273.0,233.0,230.0,-1.3%,-3.7%,0.2%
62,Total Asia Pacific,899,1002,1063,1240,1432,1979,2387,2804,3356,...,8281.0,8295.0,8377.0,8043.0,7792.0,7617.0,7650.0,0.4%,-0.6%,8.0%
63,Total World,31792,34561,37104,40418,43649,48075,50785,53554,58552,...,86794.0,88910.0,91733.0,92072.0,92798.0,95254.0,95192.0,-0.1%,1.4%,100.0%