In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
inital_df = "../notebook_data/Gross capital formation (% of GDP).csv"

In [3]:
#Read CVS
df1  = pd.read_csv(inital_df)
df1

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,28.931993,28.505697,26.647564,23.738627,23.272727,21.565251,21.397627,20.800585,NaN,NaN
1,Afghanistan,AFG,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,16.115710,16.599198,19.105702,14.201190,13.888894,11.258279,...,17.959072,16.674592,16.906255,17.343514,18.156855,19.454687,17.808790,19.174225,18.958521,17.754955
2,Angola,AGO,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,28.197310,26.424354,26.667579,26.142969,27.500462,34.202489,27.214708,24.130305,17.869421,NaN
3,Albania,ALB,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,30.308656,31.413580,28.328550,28.052503,25.674699,25.819058,25.223825,25.094501,NaN,NaN
4,Andorra,AND,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,XKX,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,32.953203,33.905909,28.961414,27.614238,25.772789,27.575340,27.184066,28.371194,29.473246,29.644330
260,"Yemen, Rep.",YEM,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,South Africa,ZAF,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,21.881353,20.930641,19.818781,23.993463,25.290148,27.272727,...,19.512981,19.720948,19.965985,21.163557,20.499494,20.917957,19.160966,18.806213,17.940380,17.589014
262,Zambia,ZMB,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,29.877515,33.644315,31.754929,34.038547,34.042891,42.791494,38.206219,41.003028,38.390521,39.231946
263,Zimbabwe,ZWE,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,20.433776,20.049978,15.598707,11.513209,11.742325,13.652441,...,18.763301,17.397766,9.856977,9.209479,9.639224,10.035640,9.861371,9.702188,9.347354,NaN

In [4]:
#Remove characters from dataframe
clean1 = df1.replace('-', np.nan)
clean1

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,28.931993,28.505697,26.647564,23.738627,23.272727,21.565251,21.397627,20.800585,NaN,NaN
1,Afghanistan,AFG,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,16.115710,16.599198,19.105702,14.201190,13.888894,11.258279,...,17.959072,16.674592,16.906255,17.343514,18.156855,19.454687,17.808790,19.174225,18.958521,17.754955
2,Angola,AGO,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,28.197310,26.424354,26.667579,26.142969,27.500462,34.202489,27.214708,24.130305,17.869421,NaN
3,Albania,ALB,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,30.308656,31.413580,28.328550,28.052503,25.674699,25.819058,25.223825,25.094501,NaN,NaN
4,Andorra,AND,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,XKX,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,32.953203,33.905909,28.961414,27.614238,25.772789,27.575340,27.184066,28.371194,29.473246,29.644330
260,"Yemen, Rep.",YEM,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,South Africa,ZAF,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,21.881353,20.930641,19.818781,23.993463,25.290148,27.272727,...,19.512981,19.720948,19.965985,21.163557,20.499494,20.917957,19.160966,18.806213,17.940380,17.589014
262,Zambia,ZMB,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,29.877515,33.644315,31.754929,34.038547,34.042891,42.791494,38.206219,41.003028,38.390521,39.231946
263,Zimbabwe,ZWE,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,20.433776,20.049978,15.598707,11.513209,11.742325,13.652441,...,18.763301,17.397766,9.856977,9.209479,9.639224,10.035640,9.861371,9.702188,9.347354,NaN

In [5]:
#Replace Nan with Zeros from dataframe
clean2 = clean1.replace(np.nan,0)
clean2

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,28.931993,28.505697,26.647564,23.738627,23.272727,21.565251,21.397627,20.800585,0.000000,0.000000
1,Afghanistan,AFG,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,16.115710,16.599198,19.105702,14.201190,13.888894,11.258279,...,17.959072,16.674592,16.906255,17.343514,18.156855,19.454687,17.808790,19.174225,18.958521,17.754955
2,Angola,AGO,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,28.197310,26.424354,26.667579,26.142969,27.500462,34.202489,27.214708,24.130305,17.869421,0.000000
3,Albania,ALB,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,30.308656,31.413580,28.328550,28.052503,25.674699,25.819058,25.223825,25.094501,0.000000,0.000000
4,Andorra,AND,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,XKX,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,32.953203,33.905909,28.961414,27.614238,25.772789,27.575340,27.184066,28.371194,29.473246,29.644330
260,"Yemen, Rep.",YEM,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
261,South Africa,ZAF,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,21.881353,20.930641,19.818781,23.993463,25.290148,27.272727,...,19.512981,19.720948,19.965985,21.163557,20.499494,20.917957,19.160966,18.806213,17.940380,17.589014
262,Zambia,ZMB,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,29.877515,33.644315,31.754929,34.038547,34.042891,42.791494,38.206219,41.003028,38.390521,39.231946
263,Zimbabwe,ZWE,Gross capital formation (% of GDP),NE.GDI.TOTL.ZS,20.433776,20.049978,15.598707,11.513209,11.742325,13.652441,...,18.763301,17.397766,9.856977,9.209479,9.639224,10.035640,9.861371,9.702188,9.347354,0.000000

In [6]:
# #Remove Zeros from dataframe
# clean3 = clean2[(clean2 != 0).all(1)]
# clean3

In [7]:
#Remove unnecessary columns from dataframe
clean4 = clean2.drop(columns=['Country Code','Indicator Name','Indicator Code'])
clean4

,Country Name,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,28.931993,28.505697,26.647564,23.738627,23.272727,21.565251,21.397627,20.800585,0.000000,0.000000
1,Afghanistan,16.115710,16.599198,19.105702,14.201190,13.888894,11.258279,8.412698,5.179283,6.472492,...,17.959072,16.674592,16.906255,17.343514,18.156855,19.454687,17.808790,19.174225,18.958521,17.754955
2,Angola,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,28.197310,26.424354,26.667579,26.142969,27.500462,34.202489,27.214708,24.130305,17.869421,0.000000
3,Albania,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,30.308656,31.413580,28.328550,28.052503,25.674699,25.819058,25.223825,25.094501,0.000000,0.000000
4,Andorra,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,32.953203,33.905909,28.961414,27.614238,25.772789,27.575340,27.184066,28.371194,29.473246,29.644330
260,"Yemen, Rep.",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
261,South Africa,21.881353,20.930641,19.818781,23.993463,25.290148,27.272727,24.781870,27.446398,25.406523,...,19.512981,19.720948,19.965985,21.163557,20.499494,20.917957,19.160966,18.806213,17.940380,17.589014
262,Zambia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,29.877515,33.644315,31.754929,34.038547,34.042891,42.791494,38.206219,41.003028,38.390521,39.231946
263,Zimbabwe,20.433776,20.049978,15.598707,11.513209,11.742325,13.652441,14.948904,17.425580,21.123278,...,18.763301,17.397766,9.856977,9.209479,9.639224,10.035640,9.861371,9.702188,9.347354,0.000000

In [8]:
# Rename columns
clean5 = clean4.rename(columns = {'Country Name': 'Year'}, inplace = False)
clean5

,Year,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,28.931993,28.505697,26.647564,23.738627,23.272727,21.565251,21.397627,20.800585,0.000000,0.000000
1,Afghanistan,16.115710,16.599198,19.105702,14.201190,13.888894,11.258279,8.412698,5.179283,6.472492,...,17.959072,16.674592,16.906255,17.343514,18.156855,19.454687,17.808790,19.174225,18.958521,17.754955
2,Angola,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,28.197310,26.424354,26.667579,26.142969,27.500462,34.202489,27.214708,24.130305,17.869421,0.000000
3,Albania,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,30.308656,31.413580,28.328550,28.052503,25.674699,25.819058,25.223825,25.094501,0.000000,0.000000
4,Andorra,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,32.953203,33.905909,28.961414,27.614238,25.772789,27.575340,27.184066,28.371194,29.473246,29.644330
260,"Yemen, Rep.",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
261,South Africa,21.881353,20.930641,19.818781,23.993463,25.290148,27.272727,24.781870,27.446398,25.406523,...,19.512981,19.720948,19.965985,21.163557,20.499494,20.917957,19.160966,18.806213,17.940380,17.589014
262,Zambia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,29.877515,33.644315,31.754929,34.038547,34.042891,42.791494,38.206219,41.003028,38.390521,39.231946
263,Zimbabwe,20.433776,20.049978,15.598707,11.513209,11.742325,13.652441,14.948904,17.425580,21.123278,...,18.763301,17.397766,9.856977,9.209479,9.639224,10.035640,9.861371,9.702188,9.347354,0.000000

In [9]:
#Transpose data for final file
Final_Clean_Transposed = clean5.set_index("Year").T
Final_Clean_Transposed

Year,Aruba,Afghanistan,Angola,Albania,Andorra,Arab World,United Arab Emirates,Argentina,Armenia,American Samoa,...,Virgin Islands (U.S.),Vietnam,Vanuatu,World,Samoa,Kosovo,"Yemen, Rep.",South Africa,Zambia,Zimbabwe
1960,0.000000,16.115710,0.000000,0.000000,0.0,0.000000,0.000000,23.479234,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,21.881353,0.000000,20.433776
1961,0.000000,16.599198,0.000000,0.000000,0.0,0.000000,0.000000,27.766447,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,20.930641,0.000000,20.049978
1962,0.000000,19.105702,0.000000,0.000000,0.0,0.000000,0.000000,21.730935,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,19.818781,0.000000,15.598707
1963,0.000000,14.201190,0.000000,0.000000,0.0,0.000000,0.000000,18.272879,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,23.993463,0.000000,11.513209
1964,0.000000,13.888894,0.000000,0.000000,0.0,0.000000,0.000000,21.473913,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,25.290148,0.000000,11.742325
1965,0.000000,11.258279,0.000000,0.000000,0.0,0.000000,0.000000,22.427676,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,27.272727,0.000000,13.652441
1966,0.000000,8.412698,0.000000,0.000000,0.0,0.000000,0.000000,20.542547,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,24.781870,0.000000,14.948904
1967,0.000000,5.179283,0.000000,0.000000,0.0,0.000000,0.000000,21.215036,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,27.446398,0.000000,17.425580
1968,0.000000,6.472492,0.000000,0.000000,0.0,0.000000,0.000000,21.690497,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,25.406523,0.000000,21.123278
1969,0.000000,6.466877,0.000000,0.000000,0.0,0.000000,0.000000,23.990605,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,26.238945,0.000000,16.891539
1970,0.000000,5.463794,0.000000,0.000000,0.0,0.000000,0.000000,24.440095,0.000000,0.0,...,0.0,0.000000,0.000000,26.911121,0.0,0.000000,0.0,28.557312,0.000000,18.337780
1971,0.000000,5.461171,0.000000,0.000000,0.0,0.000000,0.000000,24.113032,0.000000,0.0,...,0.0,0.000000,0.000000,26.526697,0.0,0.000000,0.0,30.956474,0.000000,20.171089
1972,0.000000,6.545962,0.000000,0.000000,0.0,0.000000,0.000000,23.891545,0.000000,0.0,...,0.0,0.000000,0.000000,26.164536,0.0,0.000000,0.0,26.531855,0.000000,23.704714
1973,0.000000,7.307692,0.000000,0.000000,0.0,0.000000,0.000000,20.893812,0.000000,0.0,...,0.0,0.000000,0.000000,27.054172,0.0,0.000000,0.0,26.655189,0.000000,22.875537
1974,0.000000,8.762887,0.000000,0.000000,0.0,0.000000,0.000000,22.260332,0.000000,0.0,...,0.0,0.000000,0.000000,27.896165,0.0,0.000000,0.0,30.031987,0.000000,24.743949
1975,0.000000,9.765258,0.000000,0.000000,0.0,0.000000,0.000000,29.441047,0.000000,0.0,...,0.0,0.000000,0.000000,25.909123,0.0,0.000000,0.0,32.342298,0.000000,23.632483
1976,0.000000,13.652174,0.000000,0.000000,0.0,0.000000,0.000000,30.729440,0.000000,0.0,...,0.0,0.000000,0.000000,26.450586,0.0,0.000000,0.0,30.381099,0.000000,16.110868
1977,0.000000,12.415349,0.000000,0.000000,0.0,0.000000,0.000000,30.941689,0.000000,0.0,...,0.0,0.000000,0.000000,26.629795,0.0,0.000000,0.0,29.746245,0.000000,17.185700
1978,0.000000,13.872054,0.000000,0.000000,0.0,0.000000,0.000000,27.800160,0.000000,0.0,...,0.0,0.000000,0.000000,27.184231,0.0,0.000000,0.0,26.668799,0.000000,10.695175
1979,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,25.856769,0.000000,0.0,...,0.0,0.000000,0.000000,27.392791,0.0,0.000000,0.0,27.377985,0.000000,11.409631
1980,0.000000,0.000000,0.000000,35.805835,0.0,0.000000,0.000000,25.257786,0.000000,0.0,...,0.0,0.000000,0.000000,26.883838,0.0,0.000000,0.0,31.356378,0.000000,16.936979
1981,0.000000,0.000000,0.000000,36.386116,0.0,0.000000,0.000000,22.691089,0.000000,0.0,...,0.0,0.000000,0.000000,26.389981,0.0,0.000000,0.0,34.115184,0.000000,20.815898
1982,0.000000,0.000000,0.000000,39.282900,0.0,0.000000,0.000000,21.754948,0.000000,0.0,...,0.0,0.000000,0.000000,25.109031,0.0,0.000000,0.0,26.528719,0.000000,19.053736
1983,0.000000,0.000000,0.000000,37.373346,0.0,0.000000,0.000000,20.887752,0.000000,0.0,...,0.0,0.000000,23.805173,24.601174,0.0,0.000000,0.0,27.173221,0.000000,14.305157
1984,0.000000,0.000000,0.000000,32.925535,0.0,0.000000,0.000000,19.964092,0.000000,0.0,...,0.0,0.000000,19.864694,25.344400,0.0,0.000000,0.0,25.543364,0.000000,17.035505
1985,0.000000,0.000000,0.000000,33.931959,0.0,0.000000,0.000000,17.589067,0.000000,0.0,...,0.0,0.000000,25.823422,25.319454,0.0,0.000000,0.0,22.049576,0.000000,17.819977
1986,0.000000,0.000000,0.000000,32.034835,0.0,0.000000,0.000000,17.461764,0.000000,0.0,...,0.0,14.424037,28.586041,25.095420,0.0,0.000000,0.0,21.020941,0.000000,18.056359
1987,0.000000,0.000000,0.000000,29.453870,0.0,0.000000,0.000000,19.554866,0.000000,0.0,...,0.0,13.560975,33.112997,25.373399,0.0,0.000000,0.0,17.784284,0.000000,14.936165
1988,0.000000,0.000000,0.000000,29.957542,0.0,0.000000,0.000000,18.640039,0.000000,0.0,...,0.0,17.844358,26.714801,26.239090,0.0,0.000000,0.0,21.228296,0.000000,18.701723
1989,0.000000,0.000000,0.000000,32.877072,0.0,0.000000,0.000000,15.514698,0.000000,0.0,...,0.0,14.630691,33.019206,26.624424,0.0,0.000000,0.0,22.745894,0.000000,15.037981
1990,0.000000,0.000000,0.000000,30.360947,0.0,20.916341,0.000000,13.996982,47.147684,0.0,...,0.0,12.565844,33.227268,25.923266,0.0,0.000000,0.0,19.413254,0.000000,17.376943
1991,0.000000,0.000000,0.000000,7.603111,0.0,23.999435,0.000000,14.636977,39.779144,0.0,...,0.0,15.070332,26.070260,25.392887,0.0,0.000000,0.0,19.024967,0.000000,19.103400
1992,0.000000,0.000000,0.000000,5.656684,0.0,23.268920,0.000000,16.702406,1.631258,0.0,...,0.0,17.640141,21.078189,25.210322,0.0,0.000000,0.0,16.768607,0.000000,20.237265
1993,0.000000,0.000000,0.000000,13.676137,0.0,23.722012,0.000000,19.688110,9.872203,0.0,...,0.0,24.255301,21.240215,24.917159,0.0,0.000000,0.0,15.162321,0.000000,22.774888
1994,0.000000,0.000000,0.000000,18.896585,0.0,22.384214,0.000000,19.965623,27.942158,0.0,...,0.0,25.475819,23.206520,24.930955,0.0,0.000000,0.0,17.720103,0.000000,23.729056
1995,31.138282,0.000000,0.000000,21.278513,0.0,22.458670,0.000000,18.500411,20.808569,0.0,...,0.0,27.144243,22.636617,24.806326,0.0,0.000000,0.0,19.166652,0.000000,19.660187
1996,28.460041,0.000000,0.000000,18.063784,0.0,21.010471,0.000000,19.623872,21.095447,0.0,...,0.0,28.102898,19.714505,24.650589,0.0,0.000000,0.0,18.040028,0.000000,18.541940
1997,30.231422,0.000000,0.000000,16.659496,0.0,20.371395,0.000000,20.826052,23.265679,0.0,...,0.0,28.299583,18.836425,24.676491,0.0,0.000000,0.0,17.715117,0.000000,18.133903
1998,31.705770,0.000000,0.000000,19.742581,0.0,23.259100,0.000000,20.970769,22.686352,0.0,...,0.0,29.049879,17.146018,24.418578,0.0,0.000000,0.0,17.991540,0.000000,20.750461
1999,30.870903,0.000000,0.000000,19.734708,0.0,20.468457,0.000000,17.862928,20.768880,0.0,...,0.0,27.629756,18.992831,24.101122,0.0,0.000000,0.0,17.035099,0.000000,14.396280
2000,25.495903,0.000000,30.493219,30.796259,0.0,20.227247,0.000000,17.533487,21.922331,0.0,...,0.0,29.609914,19.913998,24.448252,0.0,0.000000,0.0,16.365325,0.000000,13.569424
2001,23.712540,0.000000,30.493219,34.988682,0.0,22.631777,22.502597,15.625965,22.904355,0.0,...,0.0,31.172773,18.353789,23.948517,0.0,0.000000,0.0,15.744582,0.000000,10.266473
2002,26.906475,12.557286,30.493173,35.264046,0.0,21.733007,22.545682,10.853905,25.418297,0.0,...,0.0,33.220534,19.543689,23.358527,0.0,27.201727,0.0,16.277967,0.000000,5.000000
2003,29.215036,12.758896,30.451111,33.896887,0.0,22.345478,22.129762,14.146962,28.347950,0.0,...,0.0,35.444858,16.846242,23.817492,0.0,28.926893,0.0,17.105884,0.000000,7.999999
2004,28.779143,19.005340,30.893669,34.196767,0.0,21.938683,19.978519,17.551270,29.122558,0.0,...,0.0,35.465332,23.238487,24.685993,0.0,27.021358,0.0,18.466596,0.000000,4.509115
2005,33.581016,23.193758,27.556580,36.869666,0.0,22.281897,20.166849,18.888264,35.765439,0.0,...,0.0,33.757403,24.119310,24.921953,0.0,26.969954,0.0,18.314977,0.000000,1.525177
2006,35.161290,26.407973,23.300771,35.697515,0.0,23.398610,19.270400,18.680487,42.225458,0.0,...,0.0,34.536651,28.377183,25.404324,0.0,28.650165,0.0,20.182994,0.000000,1.571161
2007,32.514420,20.068921,25.730579,34.461979,0.0,26.617251,25.199183,20.099113,44.351623,0.0,...,0.0,39.566271,32.266439,25.791610,0.0,28.909925,0.0,20.985522,0.000000,7.109753
2008,33.251933,19.021320,30.804053,35.778422,0.0,27.597246,25.098092,19.572776,47.942836,0.0,...,0.0,36.493122,40.558703,25.620517,0.0,31.129597,0.0,23.150165,0.000000,5.127906
2009,30.292868,17.991436,42.820859,34.557802,0.0,29.436011,31.633549,16.053112,41.145051,0.0,...,0.0,37.162555,39.893119,23.391521,0.0,31.143110,0.0,20.704899,0.000000,12.746802
2010,28.931993,17.959072,28.197310,30.308656,0.0,27.535576,27.121114,17.705534,38.814755,0.0,...,0.0,35.693809,34.659559,24.207113,0.0,32.953203,0.0,19.512981,29.877515,18.763301
2011,28.505697,16.674592,26.424354,31.413580,0.0,24.912291,23.161476,18.398459,31.921799,0.0,...,0.0,29.750637,27.497072,24.547417,0.0,33.905909,0.0,19.720948,33.644315,17.397766
2012,26.647564,16.906255,26.667579,28.328550,0.0,24.079937,21.884807,16.501987,25.327906,0.0,...,0.0,27.243324,23.044949,24.404915,0.0,28.961414,0.0,19.965985,31.754929,9.856977
2013,23.738627,17.343514,26.142969,28.052503,0.0,24.974682,19.257977,17.305779,22.263533,0.0,...,0.0,26.675617,25.919818,24.310278,0.0,27.614238,0.0,21.163557,34.038547,9.209479
2014,23.272727,18.156855,27.500462,25.674699,0.0,26.034761,22.168436,17.262881,20.871866,0.0,...,0.0,26.832672,26.430621,24.470283,0.0,25.772789,0.0,20.499494,34.042891,9.639224
2015,21.565251,19.454687,34.202489,25.819058,0.0,29.725798,25.639179,17.070705,20.730530,0.0,...,0.0,27.676728,0.000000,24.297531,0.0,27.575340,0.0,20.917957,42.791494,10.035640
2016,21.397627,17.808790,27.214708,25.223825,0.0,29.609790,26.019727,17.663228,18.015509,0.0,...,0.0,26.578058,0.000000,23.913640,0.0,27.184066,0.0,19.160966,38.206219,9.861371
2017,20.800585,19.174225,24.130305,25.094501,0.0,28.096348,25.295621,18.757232,19.289686,0.0,...,0.0,26.582114,0.000000,24.222791,0.0,28.371194,0.0,18.806213,41.003028,9.702188
2018,0.000000,18.958521,17.869421,0.000000,0.0,26.093365,23.511503,20.965838,22.399739,0.0,...,0.0,26.533055,0.000000,24.382773,0.0,29.473246,0.0,17.940380,38.390521,9.347354
2019,0.000000,17.754955,0.000000,0.000000,0.0,0.000000,23.832820,18.166368,17.447586,0.0,...,0.0,26.843839,0.000000,0.000000,0.0,29.644330,0.0,17.589014,39.231946,0.000000

In [10]:
#Export Final data set
Final_Clean_Transposed.to_csv ('../final_clean_data/GDP%-YearFixed-Python.csv')