In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
inital_df = "../notebook_data/Inflation, consumer prices (annual %).csv"

In [3]:
#Read CVS
df1  = pd.read_csv(inital_df)
df1

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,2.078141,4.316297,0.627472,-2.372065,0.421441,0.474764,-0.931196,-1.028282,3.626041,4.257462
1,Afghanistan,AFG,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,2.178538,11.804186,6.441213,7.385772,4.673996,-0.661709,4.383892,4.975952,0.626149,2.302373
2,Angola,AGO,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-60.496401,13.482468,10.277905,8.777814,7.280387,-21.531694,32.377734,31.691686,20.190374,17.145320
3,Albania,ALB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,3.622335,3.429123,2.031596,1.937618,1.625865,1.896174,1.275432,1.986661,2.028060,1.411091
4,Andorra,AND,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,XKX,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,3.480508,7.336418,2.476738,1.767324,0.428958,-0.536929,0.273169,1.488234,1.053798,2.675992
260,"Yemen, Rep.",YEM,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,11.174834,19.543562,9.885387,10.968442,8.104726,NaN,NaN,NaN,NaN,NaN
261,South Africa,ZAF,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,1.288878,2.102343,1.24629,1.337968,2.53498,4.069023,...,4.063539,5.017158,5.723944,5.776404,6.136020,4.509208,6.594604,5.181082,4.504577,4.124351
262,Zambia,ZMB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,8.501761,6.429397,6.575900,6.977676,7.806876,10.110593,17.869730,6.577312,7.494572,9.150316
263,Zimbabwe,ZWE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,3.034479,3.477797,3.721087,1.631622,-0.212940,-2.409500,-1.566413,0.909733,NaN,NaN

In [4]:
#Remove characters from dataframe
clean1 = df1.replace('-', np.nan)
clean1

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,2.078141,4.316297,0.627472,-2.372065,0.421441,0.474764,-0.931196,-1.028282,3.626041,4.257462
1,Afghanistan,AFG,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,2.178538,11.804186,6.441213,7.385772,4.673996,-0.661709,4.383892,4.975952,0.626149,2.302373
2,Angola,AGO,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-60.496401,13.482468,10.277905,8.777814,7.280387,-21.531694,32.377734,31.691686,20.190374,17.145320
3,Albania,ALB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,3.622335,3.429123,2.031596,1.937618,1.625865,1.896174,1.275432,1.986661,2.028060,1.411091
4,Andorra,AND,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,XKX,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,3.480508,7.336418,2.476738,1.767324,0.428958,-0.536929,0.273169,1.488234,1.053798,2.675992
260,"Yemen, Rep.",YEM,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,11.174834,19.543562,9.885387,10.968442,8.104726,NaN,NaN,NaN,NaN,NaN
261,South Africa,ZAF,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,1.288878,2.102343,1.24629,1.337968,2.53498,4.069023,...,4.063539,5.017158,5.723944,5.776404,6.136020,4.509208,6.594604,5.181082,4.504577,4.124351
262,Zambia,ZMB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,8.501761,6.429397,6.575900,6.977676,7.806876,10.110593,17.869730,6.577312,7.494572,9.150316
263,Zimbabwe,ZWE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,3.034479,3.477797,3.721087,1.631622,-0.212940,-2.409500,-1.566413,0.909733,NaN,NaN

In [5]:
#Replace Nan with Zeros from dataframe
clean2 = clean1.replace(np.nan,0)
clean2

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,...,2.078141,4.316297,0.627472,-2.372065,0.421441,0.474764,-0.931196,-1.028282,3.626041,4.257462
1,Afghanistan,AFG,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,...,2.178538,11.804186,6.441213,7.385772,4.673996,-0.661709,4.383892,4.975952,0.626149,2.302373
2,Angola,AGO,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,...,-60.496401,13.482468,10.277905,8.777814,7.280387,-21.531694,32.377734,31.691686,20.190374,17.145320
3,Albania,ALB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,...,3.622335,3.429123,2.031596,1.937618,1.625865,1.896174,1.275432,1.986661,2.028060,1.411091
4,Andorra,AND,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,XKX,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,...,3.480508,7.336418,2.476738,1.767324,0.428958,-0.536929,0.273169,1.488234,1.053798,2.675992
260,"Yemen, Rep.",YEM,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,...,11.174834,19.543562,9.885387,10.968442,8.104726,0.000000,0.000000,0.000000,0.000000,0.000000
261,South Africa,ZAF,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,1.288878,2.102343,1.24629,1.337968,2.53498,4.069023,...,4.063539,5.017158,5.723944,5.776404,6.136020,4.509208,6.594604,5.181082,4.504577,4.124351
262,Zambia,ZMB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,...,8.501761,6.429397,6.575900,6.977676,7.806876,10.110593,17.869730,6.577312,7.494572,9.150316
263,Zimbabwe,ZWE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,...,3.034479,3.477797,3.721087,1.631622,-0.212940,-2.409500,-1.566413,0.909733,0.000000,0.000000

In [6]:
# #Remove Zeros from dataframe
# clean3 = clean2[(clean2 != 0).all(1)]
# clean3

In [7]:
#Remove unnecessary columns from dataframe
clean4 = clean2.drop(columns=['Country Code','Indicator Name','Indicator Code'])
clean4

,Country Name,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,...,2.078141,4.316297,0.627472,-2.372065,0.421441,0.474764,-0.931196,-1.028282,3.626041,4.257462
1,Afghanistan,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,...,2.178538,11.804186,6.441213,7.385772,4.673996,-0.661709,4.383892,4.975952,0.626149,2.302373
2,Angola,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,...,-60.496401,13.482468,10.277905,8.777814,7.280387,-21.531694,32.377734,31.691686,20.190374,17.145320
3,Albania,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,...,3.622335,3.429123,2.031596,1.937618,1.625865,1.896174,1.275432,1.986661,2.028060,1.411091
4,Andorra,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,...,3.480508,7.336418,2.476738,1.767324,0.428958,-0.536929,0.273169,1.488234,1.053798,2.675992
260,"Yemen, Rep.",0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,...,11.174834,19.543562,9.885387,10.968442,8.104726,0.000000,0.000000,0.000000,0.000000,0.000000
261,South Africa,1.288878,2.102343,1.24629,1.337968,2.53498,4.069023,3.48925,3.538966,1.986128,...,4.063539,5.017158,5.723944,5.776404,6.136020,4.509208,6.594604,5.181082,4.504577,4.124351
262,Zambia,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,...,8.501761,6.429397,6.575900,6.977676,7.806876,10.110593,17.869730,6.577312,7.494572,9.150316
263,Zimbabwe,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,...,3.034479,3.477797,3.721087,1.631622,-0.212940,-2.409500,-1.566413,0.909733,0.000000,0.000000

In [8]:
# Rename columns
clean5 = clean4.rename(columns = {'Country Name': 'Year'}, inplace = False)
clean5

,Year,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,...,2.078141,4.316297,0.627472,-2.372065,0.421441,0.474764,-0.931196,-1.028282,3.626041,4.257462
1,Afghanistan,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,...,2.178538,11.804186,6.441213,7.385772,4.673996,-0.661709,4.383892,4.975952,0.626149,2.302373
2,Angola,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,...,-60.496401,13.482468,10.277905,8.777814,7.280387,-21.531694,32.377734,31.691686,20.190374,17.145320
3,Albania,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,...,3.622335,3.429123,2.031596,1.937618,1.625865,1.896174,1.275432,1.986661,2.028060,1.411091
4,Andorra,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,...,3.480508,7.336418,2.476738,1.767324,0.428958,-0.536929,0.273169,1.488234,1.053798,2.675992
260,"Yemen, Rep.",0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,...,11.174834,19.543562,9.885387,10.968442,8.104726,0.000000,0.000000,0.000000,0.000000,0.000000
261,South Africa,1.288878,2.102343,1.24629,1.337968,2.53498,4.069023,3.48925,3.538966,1.986128,...,4.063539,5.017158,5.723944,5.776404,6.136020,4.509208,6.594604,5.181082,4.504577,4.124351
262,Zambia,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,...,8.501761,6.429397,6.575900,6.977676,7.806876,10.110593,17.869730,6.577312,7.494572,9.150316
263,Zimbabwe,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,...,3.034479,3.477797,3.721087,1.631622,-0.212940,-2.409500,-1.566413,0.909733,0.000000,0.000000

In [9]:
#Transpose data for final file
Final_Clean_Transposed = clean5.set_index("Year").T
Final_Clean_Transposed

Year,Aruba,Afghanistan,Angola,Albania,Andorra,Arab World,United Arab Emirates,Argentina,Armenia,American Samoa,...,Virgin Islands (U.S.),Vietnam,Vanuatu,World,Samoa,Kosovo,"Yemen, Rep.",South Africa,Zambia,Zimbabwe
1960,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.288878,0.000000,0.000000
1961,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.102343,0.000000,0.000000
1962,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,2.654867,0.000000,0.000000,1.246290,0.000000,0.000000
1963,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.689655,0.000000,0.000000,1.337968,0.000000,0.000000
1964,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,5.308219,0.000000,0.000000,2.534980,0.000000,0.000000
1965,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,2.113821,0.000000,0.000000,4.069023,0.000000,0.000000
1966,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,2.866242,0.000000,0.000000,3.489250,0.000000,0.000000
1967,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,-0.515996,0.000000,0.000000,3.538966,0.000000,0.000000
1968,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,1.711618,0.000000,0.000000,1.986128,0.000000,0.000000
1969,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,4.130546,0.000000,0.000000,3.238233,0.000000,0.000000
1970,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,2.742409,0.000000,0.000000,4.991860,0.000000,0.000000
1971,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,4.766444,0.000000,0.000000,5.957448,0.000000,0.000000
1972,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,7.506824,0.000000,0.000000,6.425694,0.000000,0.000000
1973,0.000000,0.000000,0.000000,0.000000,0.0,8.266667,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,11.764243,0.000000,0.000000,9.433973,0.000000,0.000000
1974,0.000000,0.000000,0.000000,0.000000,0.0,15.528282,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,24.987679,0.000000,0.000000,11.724122,0.000000,0.000000
1975,0.000000,0.000000,0.000000,0.000000,0.0,9.669695,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,8.787742,0.000000,0.000000,13.425944,0.000000,0.000000
1976,0.000000,0.000000,0.000000,0.000000,0.0,10.317416,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,4.903687,0.000000,0.000000,11.020402,0.000000,0.000000
1977,0.000000,0.000000,0.000000,0.000000,0.0,11.989283,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,5.736509,0.000000,14.610790,0.000000,0.000000,11.151965,0.000000,0.000000
1978,0.000000,0.000000,0.000000,0.000000,0.0,9.716033,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,6.413793,0.000000,2.058659,0.000000,0.000000,11.135608,0.000000,0.000000
1979,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,4.169367,0.000000,11.119551,0.000000,0.000000,13.293651,0.000000,0.000000
1980,0.000000,0.000000,0.000000,0.000000,0.0,9.626057,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,11.240149,0.000000,33.047243,0.000000,0.000000,13.660247,0.000000,0.000000
1981,0.000000,0.000000,0.000000,0.000000,0.0,10.758503,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,26.845638,12.482070,20.506624,0.000000,0.000000,15.254238,0.000000,0.000000
1982,0.000000,0.000000,0.000000,0.000000,0.0,8.331256,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,6.672546,10.221727,18.296225,0.000000,0.000000,14.639037,0.000000,0.000000
1983,0.000000,0.000000,0.000000,0.000000,0.0,5.493666,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,1.653348,8.669272,16.460136,0.000000,0.000000,12.303207,0.000000,0.000000
1984,0.000000,0.000000,0.000000,0.000000,0.0,8.116398,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,5.516400,8.217653,11.860068,0.000000,0.000000,11.526480,0.000000,0.000000
1985,4.032258,0.000000,0.000000,0.000000,0.0,7.254362,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,1.066153,6.807567,9.090501,0.000000,0.000000,16.294226,0.000000,0.000000
1986,1.073966,0.000000,0.000000,0.000000,0.0,7.433333,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,4.766141,5.823107,5.733558,0.000000,0.000000,18.654927,55.828221,0.000000
1987,3.643045,0.000000,0.000000,0.000000,0.0,4.222417,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,16.039395,5.756464,4.566849,0.000000,0.000000,16.160595,47.047244,0.000000
1988,3.121868,0.000000,0.000000,0.000000,0.0,5.911545,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,8.760230,7.196970,8.507868,0.000000,0.000000,12.779544,51.004016,0.000000
1989,3.991628,0.000000,0.000000,0.000000,0.0,7.740886,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,7.748049,6.999093,6.462562,0.000000,0.000000,14.730886,123.404255,0.000000
1990,5.836688,0.000000,0.000000,0.000000,0.0,8.451462,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,4.759441,8.215536,15.238463,0.000000,0.000000,14.320976,107.023809,0.000000
1991,5.555556,0.000000,0.000000,0.000000,0.0,9.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,6.469136,8.996939,-1.819198,0.000000,36.000000,15.334782,97.642323,0.000000
1992,3.873375,0.000000,0.000000,226.005421,0.0,9.359752,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,4.058442,7.636109,9.031138,0.000000,29.411765,13.874703,165.706527,0.000000
1993,5.215560,0.000000,0.000000,85.004751,0.0,9.370344,0.000000,0.000000,0.000000,0.0,...,0.0,0.000000,3.565857,7.144587,1.715091,0.000000,35.752298,9.717448,183.312041,0.000000
1994,6.311080,0.000000,0.000000,22.565053,0.0,5.112599,0.000000,0.000000,3373.759443,0.0,...,0.0,0.000000,2.302561,10.143683,12.080382,0.000000,49.394155,8.938544,54.601322,0.000000
1995,3.361391,0.000000,0.000000,7.793219,0.0,6.543791,0.000000,0.000000,175.951325,0.0,...,0.0,0.000000,2.229701,9.073536,-2.903529,0.000000,55.081107,8.680426,34.929587,0.000000
1996,3.225288,0.000000,0.000000,12.725478,0.0,4.681306,0.000000,0.000000,18.681186,0.0,...,0.0,5.675000,0.906344,6.550973,5.374620,0.000000,30.733733,7.354129,43.073098,0.000000
1997,2.999948,0.000000,0.000000,33.180274,0.0,3.601161,0.000000,0.000000,13.960764,0.0,...,0.0,3.209526,2.830702,5.536007,6.861824,0.000000,2.176727,8.597771,24.418722,0.000000
1998,1.869489,0.000000,0.000000,20.642859,0.0,3.417319,0.000000,0.000000,8.672486,0.0,...,0.0,7.266198,3.282160,5.110250,2.218835,0.000000,5.976509,6.880553,24.458456,0.000000
1999,2.280372,0.000000,0.000000,0.389438,0.0,2.669374,0.000000,0.000000,0.648246,0.0,...,0.0,4.117102,1.998975,3.079499,0.265120,0.000000,8.660219,5.181488,26.787697,0.000000
2000,4.044021,0.000000,0.000000,0.050018,0.0,1.853790,0.000000,0.000000,-0.790884,0.0,...,0.0,-1.710337,2.537688,3.494465,0.966782,0.000000,4.590000,5.338952,26.030412,0.000000
2001,2.883604,0.000000,0.000000,3.107588,0.0,1.772204,0.000000,0.000000,3.145905,0.0,...,0.0,-0.431545,3.577555,3.878938,3.838285,0.000000,11.911591,5.701905,21.393782,0.000000
2002,3.315247,0.000000,0.000000,7.770526,0.0,1.832994,0.000000,0.000000,1.060049,0.0,...,0.0,3.830828,1.963568,2.907999,8.050314,0.000000,12.238534,9.494707,22.233345,0.000000
2003,3.656365,0.000000,98.224144,0.484003,0.0,2.712592,0.000000,0.000000,4.721553,0.0,...,0.0,3.234648,3.016241,3.020643,0.115830,-1.084813,10.832361,5.679418,21.401578,0.000000
2004,2.529129,0.000000,43.542107,2.280019,0.0,3.632280,0.000000,0.000000,6.961261,0.0,...,0.0,7.754947,1.418919,3.382647,16.313151,-1.064727,12.515095,-0.692030,17.967789,0.000000
2005,3.397787,12.686269,22.953514,2.366582,0.0,3.493685,0.000000,0.000000,0.638928,0.0,...,0.0,8.284572,1.199201,4.112184,1.856764,-1.385189,11.811264,2.062852,18.324440,0.000000
2006,3.608024,6.784597,13.305210,2.370728,0.0,3.544986,0.000000,0.000000,2.892357,0.0,...,0.0,7.418017,2.040816,4.267175,3.700087,0.621647,10.844799,3.243902,9.019572,0.000000
2007,5.392568,8.680571,12.251497,2.932682,0.0,4.743906,0.000000,0.000000,4.407361,0.0,...,0.0,8.344449,3.935484,4.827047,5.577064,4.358497,7.905118,6.177812,10.657350,0.000000
2008,8.955987,26.418664,12.475829,3.363138,0.0,11.270665,12.250420,0.000000,8.949953,0.0,...,0.0,23.115448,4.841713,8.949953,11.565907,9.350418,18.976257,10.055282,12.445579,0.000000
2009,-2.135429,-6.811161,13.730284,2.231397,0.0,2.920897,1.561813,0.000000,3.406767,0.0,...,0.0,6.716983,4.297066,2.928564,6.324953,-2.410264,5.407761,7.264562,13.395255,0.000000
2010,2.078141,2.178538,-60.496401,3.622335,0.0,3.911062,0.877983,0.000000,8.176361,0.0,...,0.0,9.207466,2.762695,3.326345,0.777007,3.480508,11.174834,4.063539,8.501761,3.034479
2011,4.316297,11.804186,13.482468,3.429123,0.0,4.753164,0.877347,0.000000,7.650008,0.0,...,0.0,18.677732,0.873793,4.839403,5.235416,7.336418,19.543562,5.017158,6.429397,3.477797
2012,0.627472,6.441213,10.277905,2.031596,0.0,4.611844,0.662269,0.000000,2.558020,0.0,...,0.0,9.094703,1.347404,3.707818,2.049019,2.476738,9.885387,5.723944,6.575900,3.721087
2013,-2.372065,7.385772,8.777814,1.937618,0.0,3.238108,1.101118,0.000000,5.789668,0.0,...,0.0,6.592675,1.458934,2.605818,0.610086,1.767324,10.968442,5.776404,6.977676,1.631622
2014,0.421441,4.673996,7.280387,1.625865,0.0,2.772885,2.346269,0.000000,2.981309,0.0,...,0.0,4.084554,0.798864,2.346269,-0.406816,0.428958,8.104726,6.136020,7.806876,-0.212940
2015,0.474764,-0.661709,-21.531694,1.896174,0.0,1.814077,4.069966,0.000000,3.731691,0.0,...,0.0,0.631201,2.483269,1.393330,0.724470,-0.536929,0.000000,4.509208,10.110593,-2.409500
2016,-0.931196,4.383892,32.377734,1.275432,0.0,2.068840,1.617488,0.000000,-1.403608,0.0,...,0.0,2.668248,0.842069,1.486007,1.304719,0.273169,0.000000,6.594604,17.869730,-1.566413
2017,-1.028282,4.975952,31.691686,1.986661,0.0,1.966826,1.966826,0.000000,0.969553,0.0,...,0.0,3.520257,3.084526,2.233522,1.749897,1.488234,0.000000,5.181082,6.577312,0.909733
2018,3.626041,0.626149,20.190374,2.028060,0.0,2.458142,3.068634,34.277224,2.520234,0.0,...,0.0,3.539628,2.330964,2.458142,4.197459,1.053798,0.000000,4.504577,7.494572,0.000000
2019,4.257462,2.302373,17.145320,1.411091,0.0,1.336016,-1.931081,53.548304,1.443447,0.0,...,0.0,2.795824,2.762520,2.318441,0.982327,2.675992,0.000000,4.124351,9.150316,0.000000

In [10]:
#Export Final data set
Final_Clean_Transposed.to_csv ('../final_clean_data/InflationAnnual%-YearFixed-Python.csv')