In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
inital_df = "../notebook_data/Taxes on goods and services (% of revenue).csv"

In [3]:
#Read CVS
df1  = pd.read_csv(inital_df)
df1

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.030144,2.622425,3.119214,2.535723,2.550026,2.654241,7.055293,8.598224,NaN,NaN
2,Angola,AGO,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.013951,3.631330,3.748301,4.295908,5.174118,6.740552,8.063090,7.445482,NaN,NaN
3,Albania,ALB,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,55.571622,55.405082,54.174790,55.581329,54.627694,55.926813,53.294789,53.132719,NaN
4,Andorra,AND,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,XKX,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,"Yemen, Rep.",YEM,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,South Africa,ZAF,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,35.154277,33.103079,34.089478,33.145273,33.091565,33.977348,33.315927,32.817231,34.011405,NaN
262,Zambia,ZMB,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,29.790072,23.912360,29.801916,38.137973,42.645346,32.436842,27.856806,36.894517,38.004259,NaN
263,Zimbabwe,ZWE,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,28.959150,33.544017,35.814073,NaN,NaN,46.878657,46.781836,47.064242,41.234977,NaN

In [4]:
#Remove characters from dataframe
clean1 = df1.replace('-', np.nan)
clean1

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.030144,2.622425,3.119214,2.535723,2.550026,2.654241,7.055293,8.598224,NaN,NaN
2,Angola,AGO,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.013951,3.631330,3.748301,4.295908,5.174118,6.740552,8.063090,7.445482,NaN,NaN
3,Albania,ALB,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,55.571622,55.405082,54.174790,55.581329,54.627694,55.926813,53.294789,53.132719,NaN
4,Andorra,AND,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,XKX,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,"Yemen, Rep.",YEM,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,South Africa,ZAF,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,35.154277,33.103079,34.089478,33.145273,33.091565,33.977348,33.315927,32.817231,34.011405,NaN
262,Zambia,ZMB,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,29.790072,23.912360,29.801916,38.137973,42.645346,32.436842,27.856806,36.894517,38.004259,NaN
263,Zimbabwe,ZWE,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,28.959150,33.544017,35.814073,NaN,NaN,46.878657,46.781836,47.064242,41.234977,NaN

In [5]:
#Replace Nan with Zeros from dataframe
clean2 = clean1.replace(np.nan,0)
clean2

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
1,Afghanistan,AFG,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,3.030144,2.622425,3.119214,2.535723,2.550026,2.654241,7.055293,8.598224,0.000000,0.0
2,Angola,AGO,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,6.013951,3.631330,3.748301,4.295908,5.174118,6.740552,8.063090,7.445482,0.000000,0.0
3,Albania,ALB,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,55.571622,55.405082,54.174790,55.581329,54.627694,55.926813,53.294789,53.132719,0.0
4,Andorra,AND,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,XKX,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
260,"Yemen, Rep.",YEM,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
261,South Africa,ZAF,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,35.154277,33.103079,34.089478,33.145273,33.091565,33.977348,33.315927,32.817231,34.011405,0.0
262,Zambia,ZMB,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,29.790072,23.912360,29.801916,38.137973,42.645346,32.436842,27.856806,36.894517,38.004259,0.0
263,Zimbabwe,ZWE,Taxes on goods and services (% of revenue),GC.TAX.GSRV.RV.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,28.959150,33.544017,35.814073,0.000000,0.000000,46.878657,46.781836,47.064242,41.234977,0.0

In [6]:
#Remove Zeros from dataframe
# clean3 = clean2[(clean2 != 0).all(1)]
# clean3

Empty DataFrame
Columns: [Country Name, Country Code, Indicator Name, Indicator Code, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]
Index: []

[0 rows x 64 columns]

In [12]:
#Remove unnecessary columns from dataframe
clean4 = clean2.drop(columns=['Country Code','Indicator Name','Indicator Code'])
clean4

,Country Name,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
1,Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.030144,2.622425,3.119214,2.535723,2.550026,2.654241,7.055293,8.598224,0.000000,0.0
2,Angola,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.013951,3.631330,3.748301,4.295908,5.174118,6.740552,8.063090,7.445482,0.000000,0.0
3,Albania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,55.571622,55.405082,54.174790,55.581329,54.627694,55.926813,53.294789,53.132719,0.0
4,Andorra,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
260,"Yemen, Rep.",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
261,South Africa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,35.154277,33.103079,34.089478,33.145273,33.091565,33.977348,33.315927,32.817231,34.011405,0.0
262,Zambia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,29.790072,23.912360,29.801916,38.137973,42.645346,32.436842,27.856806,36.894517,38.004259,0.0
263,Zimbabwe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,28.959150,33.544017,35.814073,0.000000,0.000000,46.878657,46.781836,47.064242,41.234977,0.0

In [13]:
# Rename columns
clean5 = clean4.rename(columns = {'Country Name': 'Year'}, inplace = False)
clean5

,Year,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
1,Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.030144,2.622425,3.119214,2.535723,2.550026,2.654241,7.055293,8.598224,0.000000,0.0
2,Angola,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.013951,3.631330,3.748301,4.295908,5.174118,6.740552,8.063090,7.445482,0.000000,0.0
3,Albania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,55.571622,55.405082,54.174790,55.581329,54.627694,55.926813,53.294789,53.132719,0.0
4,Andorra,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
260,"Yemen, Rep.",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
261,South Africa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,35.154277,33.103079,34.089478,33.145273,33.091565,33.977348,33.315927,32.817231,34.011405,0.0
262,Zambia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,29.790072,23.912360,29.801916,38.137973,42.645346,32.436842,27.856806,36.894517,38.004259,0.0
263,Zimbabwe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,28.959150,33.544017,35.814073,0.000000,0.000000,46.878657,46.781836,47.064242,41.234977,0.0

In [14]:
#Transpose data for final file
Final_Clean_Transposed = clean5.set_index("Year").T
Final_Clean_Transposed

Year,Aruba,Afghanistan,Angola,Albania,Andorra,Arab World,United Arab Emirates,Argentina,Armenia,American Samoa,...,Virgin Islands (U.S.),Vietnam,Vanuatu,World,Samoa,Kosovo,"Yemen, Rep.",South Africa,Zambia,Zimbabwe
1960,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
1961,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
1962,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
1963,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
1964,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
1965,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
1966,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
1967,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
1968,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
1969,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
1970,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
1971,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
1972,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,23.672231,0.000000,0.000000
1973,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,21.338112,0.000000,0.000000
1974,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,17.833399,0.000000,0.000000
1975,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,19.772879,0.000000,0.000000
1976,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,22.132254,0.000000,0.000000
1977,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,22.213449,0.000000,0.000000
1978,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,25.692273,0.000000,0.000000
1979,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,26.532887,0.000000,0.000000
1980,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,25.065981,0.000000,0.000000
1981,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,27.310715,0.000000,0.000000
1982,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,29.037971,0.000000,0.000000
1983,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,30.256505,0.000000,0.000000
1984,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,33.708544,0.000000,0.000000
1985,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,32.815188,0.000000,0.000000
1986,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,31.825884,0.000000,0.000000
1987,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,33.929069,0.000000,0.000000
1988,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,34.698532,0.000000,0.000000
1989,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,33.906841,0.000000,0.000000
1990,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,21.960248,0.000000,0.0,...,0.0,0.0,25.858048,0.000000,0.000000,0.0,0.0,34.881995,37.447859,0.000000
1991,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,27.524267,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,34.075892,28.052848,0.000000
1992,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,29.982107,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,33.301809,30.518633,0.000000
1993,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,33.879287,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,37.278386,18.333186,0.000000
1994,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,33.396140,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,38.426803,26.855265,0.000000
1995,0.0,0.000000,0.000000,39.069787,0.0,0.0,0.000000,36.482069,0.000000,0.0,...,0.0,0.0,34.296850,0.000000,0.000000,0.0,0.0,36.770779,22.448448,0.000000
1996,0.0,0.000000,0.000000,33.264055,0.0,0.0,0.000000,39.253774,0.000000,0.0,...,0.0,0.0,33.454030,0.000000,0.000000,0.0,0.0,35.094950,47.462959,0.000000
1997,0.0,0.000000,0.000000,34.164020,0.0,0.0,15.118972,40.741457,0.000000,0.0,...,0.0,0.0,38.066076,0.000000,0.000000,0.0,0.0,35.570757,50.368421,0.000000
1998,0.0,0.000000,0.000000,36.069109,0.0,0.0,15.563190,41.789041,0.000000,0.0,...,0.0,0.0,41.677903,33.792780,0.000000,0.0,0.0,35.072970,31.671133,0.000000
1999,0.0,0.000000,4.524335,0.000000,0.0,0.0,17.218183,42.111980,0.000000,0.0,...,0.0,0.0,50.126469,0.000000,0.000000,0.0,0.0,34.603686,35.908697,0.000000
2000,0.0,0.000000,3.091564,0.000000,0.0,0.0,0.000000,43.864116,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,34.533396,0.000000,0.000000
2001,0.0,0.000000,21.081572,0.000000,0.0,0.0,0.000000,43.825315,0.000000,0.0,...,0.0,0.0,0.000000,33.039462,0.000000,0.0,0.0,33.103691,0.000000,0.000000
2002,0.0,0.000000,7.153503,43.074407,0.0,0.0,0.000000,37.445871,0.000000,0.0,...,0.0,0.0,0.000000,32.575330,0.000000,0.0,0.0,33.711051,0.000000,0.000000
2003,0.0,0.000000,7.749278,45.678025,0.0,0.0,0.000000,34.251352,0.000000,0.0,...,0.0,0.0,0.000000,33.607547,0.000000,0.0,0.0,35.289723,29.572173,0.000000
2004,0.0,0.000000,7.687417,48.696260,0.0,0.0,0.000000,37.166920,31.321181,0.0,...,0.0,0.0,0.000000,34.915823,0.000000,0.0,0.0,36.189834,31.490151,0.000000
2005,0.0,0.000000,6.537796,0.000000,0.0,0.0,0.000000,37.233223,32.260690,0.0,...,0.0,0.0,0.000000,34.949972,0.000000,0.0,0.0,35.191100,29.508129,0.000000
2006,0.0,5.758617,3.551998,0.000000,0.0,0.0,0.000000,35.891689,30.170863,0.0,...,0.0,0.0,0.000000,33.734591,0.000000,0.0,0.0,34.426156,32.760521,0.000000
2007,0.0,4.312936,4.125171,0.000000,0.0,0.0,0.000000,33.928566,41.050812,0.0,...,0.0,0.0,0.000000,33.746476,0.000000,0.0,0.0,33.680986,28.711553,0.000000
2008,0.0,1.780590,4.846149,0.000000,0.0,0.0,0.000000,31.676975,43.449190,0.0,...,0.0,0.0,0.000000,32.268633,0.000000,0.0,0.0,31.348824,31.875183,0.000000
2009,0.0,2.999527,12.046253,0.000000,0.0,0.0,0.000000,29.458708,40.572307,0.0,...,0.0,0.0,38.535503,31.557385,0.000000,0.0,0.0,31.511576,28.269240,30.524038
2010,0.0,3.030144,6.013951,0.000000,0.0,0.0,0.000000,28.603677,42.503425,0.0,...,0.0,0.0,47.068818,31.875890,0.000000,0.0,0.0,35.154277,29.790072,28.959150
2011,0.0,2.622425,3.631330,55.571622,0.0,0.0,6.989005,29.653887,39.514285,0.0,...,0.0,0.0,49.843240,33.264196,0.000000,0.0,0.0,33.103079,23.912360,33.544017
2012,0.0,3.119214,3.748301,55.405082,0.0,0.0,8.166584,29.574197,42.151875,0.0,...,0.0,0.0,56.616131,33.271756,44.945002,0.0,0.0,34.089478,29.801916,35.814073
2013,0.0,2.535723,4.295908,54.174790,0.0,0.0,8.263178,29.165483,41.707723,0.0,...,0.0,0.0,62.175838,32.787076,47.489523,0.0,0.0,33.145273,38.137973,0.000000
2014,0.0,2.550026,5.174118,55.581329,0.0,0.0,8.269640,27.594534,44.159074,0.0,...,0.0,0.0,58.776612,33.191709,44.125472,0.0,0.0,33.091565,42.645346,0.000000
2015,0.0,2.654241,6.740552,54.627694,0.0,0.0,0.982609,28.000035,39.483961,0.0,...,0.0,0.0,37.645983,33.724915,47.424974,0.0,0.0,33.977348,32.436842,46.878657
2016,0.0,7.055293,8.063090,55.926813,0.0,0.0,0.655505,27.241612,37.809307,0.0,...,0.0,0.0,36.204418,34.248831,49.193430,0.0,0.0,33.315927,27.856806,46.781836
2017,0.0,8.598224,7.445482,53.294789,0.0,0.0,1.315612,30.252266,38.468326,0.0,...,0.0,0.0,37.694728,33.333664,48.964494,0.0,0.0,32.817231,36.894517,47.064242
2018,0.0,0.000000,0.000000,53.132719,0.0,0.0,1.263103,33.348220,40.077763,0.0,...,0.0,0.0,35.406407,34.011405,47.353219,0.0,0.0,34.011405,38.004259,41.234977
2019,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000

In [15]:
#Export Final data set
Final_Clean_Transposed.to_csv ('../final_clean_data/Taxes%-YearFixed-Python.csv')